
version: "3.7"

services:
        web:
                build: web
                ports:
                        - 5555:8000
                volumes:
                        - ./web/app:/app
                environment:
#                        - SENTRY_DSN=${SENTRY_DSN}
                        - ENABLE_METRICS=${ENABLE_METRICS}
                command: gunicorn -b 0.0.0.0 -w 1 -k uvicorn.workers.UvicornWorker --access-logfile=- --error-logfile=- --log-level debug --reload app:app
                secrets:
                 - DISCORD_WEBHOOK_URL
                 - GITHUB_SECRET
                 - SENTRY_DSN
                 - SPAM_SECRET
                restart: unless-stopped



        prometheus:
                image: prom/prometheus:v2.30.3
                ports:
                     - 9090:9090
                volumes:
                     - ./prometheus:/etc/prometheus
                     - prometheus-data:/prometheus
                command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml


volumes:
      prometheus-data:



secrets:
 DISCORD_WEBHOOK_URL:
  file: secrets/DISCORD_WEBHOOK_URL
 GITHUB_SECRET:
  file: secrets/GITHUB_SECRET
 SENTRY_DSN:
  file: secrets/SENTRY_DSN
 SPAM_SECRET:
  file: secrets/SPAM_SECRET


