
version: "3.7"

services:
        web:
                build: web
                ports:
                        - 5555:8000
                volumes:
                        - ./web/app:/app
                environment:
                        - FLASK_DEBUG=${FLASK_DEBUG}
                        - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
                        - GITHUB_SECRET=${GITHUB_SECRET}
                command: gunicorn -b 0.0.0.0 -w 1 -k uvicorn.workers.UvicornWorker --access-logfile=-  app:app

                restart: unless-stopped


