
version: "3.7"

services:
        web:
                build: web
                ports:
                        - 5555:8000
                volumes:
                        - ./web/app:/app
                environment:
                        - FLASK_DEBUG=${FLASK_DEBUG}
                        - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
                        - GITHUB_SECRET=${GITHUB_SECRET}
#                command: "/home/user/.local/bin/flask run --host=0.0.0.0 --port 5555"
                command: "gunicorn  -b 0.0.0.0  app:app"

                restart: unless-stopped


