global:
  scrape_interval: 1m
  scrape_timeout: 20s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'web:8000'